### ISSUE TITLE
Structs cannot handle null type

### ISSUE THREAD

**Issue by kylesurowiec** [kylesurowiec/swapi-rust#10]
`https://swapi.co/api/species/2/` returns `null` for field `homeworld` instead of expected `String`.

**Comment by d-jo** [comment]
I see, it throws a decoding error in the appropriate query method. 

One possible fix I see would be to manually implement Deserialize to return partial results when a null value is encountered. Another would be passing the error up via a Result and letting the users handle it.

If planned correctly, we can manually implementing Deserialize for partial results and also fix the generic query method at the same time. Although, this is a lot more time consuming than just passing the Err up for the users to deal with.

**Comment by kylesurowiec** [comment]
I tried this as well and it worked.
  

  
https://doc.rust-lang.org/std/option/
  

  
I submitted a PR to fix the null value coming through since it’s the only spot in the api that uses null instead of “n/a”. Doesn’t look like the owner is active at the moment. Maybe try mentioning him in the PR?
  

  
  

  
  
>
